In [2]:
import numpy as np

In [3]:
#Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [13]:
N = int(input('введите число элементов'))
x = np.arange(N *-1, 0, 1) +1
print(x*-1)
#вычитаю единицу из N, чтобы начиналось с 9, а не 10. т.к. задано не число элементов, а кооординаты начала и конца

введите число элементов10
[9 8 7 6 5 4 3 2 1 0]


In [4]:
#Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [7]:
n = int(input('введите число элементов'))
diag_matrix = np.diag(np.arange(n+1), k=0)
diag_matrix = diag_matrix * -1
for i, row in enumerate(diag_matrix):
    row[i] = row[i] + n
print(diag_matrix)

total_sum = 0
for i, numbers in enumerate(diag_matrix):
    total_sum += numbers[i]
print('сумма значений по диагонали равна ', total_sum)

введите число элементов10
[[10  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]
сумма значений по диагонали равна  55


In [5]:
#Решите систему уравнений:
#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3

In [21]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

In [22]:
from numpy import linalg

In [23]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [24]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [31]:
solve = linalg.solve(a, b)
print(f" Ответ: x ~ {round(solve[0], 2)}, y ~ {round(solve[1], 2)}, z ~ {round(solve[2], 2)})  ")

 Ответ: x ~ 0.47, y ~ 3.84, z ~ -5.56)  
